--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Mrchlldev/MCrates
build-by-default: true
branches:
- main
projects:
  MCrates:
    path: ""
    icon: "20240814_111146.jpg"
    libs:
      - src: CortexPE\Commando
        version: ^3.1.0
      - src: Muqsit/invmenu/InvMenu
        version: ^4.6.5
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
